<?php
function getList01() {
    return [
        
        ['name' => 'Apéro (1)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (2)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (3)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (4)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (5)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (6)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (7)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (8)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (9)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (10)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (11)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (12)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (13)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (14)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (15)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (16)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (17)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (18)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (19)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Apéro (20)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => ''],

        ['name' => 'Bouteille (1)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (2)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (3)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (4)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (5)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (6)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (7)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (8)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (9)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (10)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (11)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (12)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (13)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (14)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (15)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (16)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (17)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (18)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (19)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (20)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (21)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (22)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (23)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (24)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (25)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (26)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (27)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (28)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (29)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (30)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (31)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (32)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (33)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (34)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (35)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (36)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (37)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (38)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (39)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (40)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (41)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (42)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (43)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (44)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (45)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (46)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (47)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (48)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (49)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (50)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (51)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (52)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (53)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (54)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (55)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (56)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (57)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (58)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (59)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (60)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (61)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (62)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (63)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (64)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (65)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

    ];
};