<?php
function getList02() {
    return [
        
        ['name' => 'Bouteille (68)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (69)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (70)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (71)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (72)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (73)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (74)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (75)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (76)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (77)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (78)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (79)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (80)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (81)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (82)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (83)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (84)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (85)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (86)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (87)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (88)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (89)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (90)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (91)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (92)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (93)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (94)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (95)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (96)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (97)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (98)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (99)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (100)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (101)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (102)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (103)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (104)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (105)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (106)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (107)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (108)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (109)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (110)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (111)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (112)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (113)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (114)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (115)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (116)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (117)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (118)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (119)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (120)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (121)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (122)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (123)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (124)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (125)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Bouteille (126)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Bouteille'],

        ['name' => 'Canapé palette (1)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (2)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (3)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (4)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (5)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (6)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (7)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Canapé palette (8)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Canapé palette'],

        ['name' => 'Horloge (1)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (2)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (3)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (4)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (5)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (6)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (7)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (8)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (9)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (10)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (11)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (12)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (13)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (14)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (15)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (16)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (17)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (18)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],

        ['name' => 'Horloge (19)',
        'title' => '',
        'price' => '',
        'description' => '',
        'category' => 'Horloge'],


    ];
};
